Import libraries

In [3]:
import pandas as pd
import numpy as np
#preprocessing tools
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.utils import resample
#classification models
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
#for model evaluation
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score


Load dataset

In [4]:
df=pd.read_csv("C:/Users/Admin/Downloads/student-scores.csv")
df.head()

,id,first_name,last_name,email,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score
0,1,Paul,Casey,paul.casey.1@gslingacademy.com,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87
1,2,Danielle,Sandoval,danielle.sandoval.2@gslingacademy.com,female,False,2,False,47,Doctor,90,86,96,100,90,88,90
2,3,Tina,Andrews,tina.andrews.3@gslingacademy.com,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94
3,4,Tara,Clark,tara.clark.4@gslingacademy.com,female,False,5,False,3,Artist,71,74,88,80,89,63,86
4,5,Anthony,Campos,anthony.campos.5@gslingacademy.com,male,False,5,False,10,Unknown,84,77,65,65,80,74,76


In [5]:
df.columns

Index(['id', 'first_name', 'last_name', 'email', 'gender', 'part_time_job',
       'absence_days', 'extracurricular_activities', 'weekly_self_study_hours',
       'career_aspiration', 'math_score', 'history_score', 'physics_score',
       'chemistry_score', 'biology_score', 'english_score', 'geography_score'],
      dtype='object')

Data cleaning and preprocessing

In [6]:
#drop columns
df.drop(columns=['id', 'first_name', 'last_name', 'email'],inplace=True)
df.head()

,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score
0,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87
1,female,False,2,False,47,Doctor,90,86,96,100,90,88,90
2,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94
3,female,False,5,False,3,Artist,71,74,88,80,89,63,86
4,male,False,5,False,10,Unknown,84,77,65,65,80,74,76


In [7]:
df.isnull().sum()

gender                        0
part_time_job                 0
absence_days                  0
extracurricular_activities    0
weekly_self_study_hours       0
career_aspiration             0
math_score                    0
history_score                 0
physics_score                 0
chemistry_score               0
biology_score                 0
english_score                 0
geography_score               0
dtype: int64

Create new feature

In [8]:
df['total_score']=df['math_score']+df[ 'history_score']+df[ 'physics_score']+df['chemistry_score']+df[ 'biology_score']+df[ 'english_score']+df[ 'geography_score']
df.columns

Index(['gender', 'part_time_job', 'absence_days', 'extracurricular_activities',
       'weekly_self_study_hours', 'career_aspiration', 'math_score',
       'history_score', 'physics_score', 'chemistry_score', 'biology_score',
       'english_score', 'geography_score', 'total_score'],
      dtype='object')

Encoding

In [9]:
encoder=LabelEncoder()
df['gender']=encoder.fit_transform(df['gender'])
df['part_time_job']=encoder.fit_transform(df['part_time_job'])
df['extracurricular_activities']=encoder.fit_transform(df['extracurricular_activities'])
df.head()


,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,total_score
0,1,0,3,0,27,Lawyer,73,81,93,97,63,80,87,574
1,0,0,2,0,47,Doctor,90,86,96,100,90,88,90,640
2,0,0,9,1,13,Government Officer,81,97,95,96,65,77,94,605
3,0,0,5,0,3,Artist,71,74,88,80,89,63,86,551
4,1,0,5,0,10,Unknown,84,77,65,65,80,74,76,521


In [10]:
df['career_aspiration'].values


array(['Lawyer', 'Doctor', 'Government Officer', ..., 'Software Engineer',
       'Business Owner', 'Accountant'], dtype=object)

In [11]:
df['career_aspiration'].dtype

dtype('O')

In [12]:
career_map = {
    'Lawyer': 0,
    'Doctor': 1,
    'Government Officer': 2,
    'Artist': 3,
    'Unknown': 4,
    'Software Engineer': 5,
    'Teacher': 6,
    'Business Owner': 7,
    'Banker': 8,
    'Accountant': 9,
    'Real Estate Developer': 10,
    'Stock Investor': 11,
    'Construction Engineer': 12,
    'Game Developer': 13,
    'Designer': 14,
    'Scientist': 15,
    'Writer': 16
}

df['career_aspiration'] = df['career_aspiration'].map(career_map)
df['career_aspiration'].isna().sum()

0

In [13]:
df.head(10)

,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,total_score
0,1,0,3,0,27,0,73,81,93,97,63,80,87,574
1,0,0,2,0,47,1,90,86,96,100,90,88,90,640
2,0,0,9,1,13,2,81,97,95,96,65,77,94,605
3,0,0,5,0,3,3,71,74,88,80,89,63,86,551
4,1,0,5,0,10,4,84,77,65,65,80,74,76,521
5,0,0,2,0,26,4,93,100,67,78,72,80,84,574
6,1,0,3,1,23,5,99,96,97,73,88,76,64,593
7,1,1,2,1,34,5,95,95,82,63,84,70,85,574
8,1,0,6,0,25,4,94,68,94,85,81,74,72,568
9,0,0,3,1,18,6,98,69,88,71,67,71,73,537


In [14]:
df.columns

Index(['gender', 'part_time_job', 'absence_days', 'extracurricular_activities',
       'weekly_self_study_hours', 'career_aspiration', 'math_score',
       'history_score', 'physics_score', 'chemistry_score', 'biology_score',
       'english_score', 'geography_score', 'total_score'],
      dtype='object')

Scaling:Normalization

In [15]:
# Define the columns to scale
scale_cols = ['absence_days', 'weekly_self_study_hours', 'math_score', 'history_score',
              'physics_score', 'chemistry_score', 'biology_score',
              'english_score', 'geography_score']

scaler = StandardScaler()

df[scale_cols] = scaler.fit_transform(df[scale_cols])
df

,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,total_score
0,1,0,-0.253175,0,0.762334,0,-0.790525,0.052463,0.930377,1.331147,-1.208673,-0.106245,0.525321,574
1,0,0,-0.633604,0,2.411605,1,0.495250,0.445147,1.169682,1.565986,0.759435,0.559086,0.783168,640
2,0,0,2.029397,1,-0.392155,2,-0.185454,1.309054,1.089913,1.252867,-1.062888,-0.355744,1.126964,605
3,0,0,0.507682,0,-1.216791,3,-0.941792,-0.497296,0.531536,0.000391,0.686542,-1.520075,0.439372,551
4,1,0,0.507682,0,-0.639546,4,0.041447,-0.261685,-1.303134,-1.173804,0.030506,-0.605244,-0.420119,521
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1,0,-0.633604,0,1.009725,12,-0.034186,-0.261685,0.212463,-0.547567,-0.333959,0.226421,0.095575,558
1996,1,0,-0.633604,0,0.185089,5,0.419616,-1.204128,-0.664988,0.000391,0.540756,-1.187409,-0.677966,534
1997,0,0,0.507682,0,-0.309692,5,1.024687,0.366610,-1.462670,1.018028,-0.844209,1.058085,-0.248221,578
1998,0,1,2.409825,1,-1.051864,7,-2.454469,1.230517,-0.744756,0.704909,1.123899,0.559086,-0.506068,566


Data Balancing

In [16]:
df['career_aspiration'].value_counts()

career_aspiration
5     315
7     309
4     223
8     169
0     138
9     126
1     119
10     83
11     73
12     68
3      67
13     63
2      61
6      59
14     56
15     39
16     32
Name: count, dtype: int64

In [17]:
# Split the dataframe into separate DataFrames for each class
classes = df['career_aspiration'].unique()
df_list = [df[df['career_aspiration'] == label] for label in classes]

# Find the class with the maximum count
max_size = max([len(sub_df) for sub_df in df_list])

# Resample each class to match the max_size
df_upsampled = [resample(sub_df,
                         replace=True,      # sample with replacement
                         n_samples=max_size, # to match majority class
                         random_state=42)    # reproducible results
                for sub_df in df_list]

# Combine back into a single DataFrame
df = pd.concat(df_upsampled)

# Shuffle the dataset
df = df.sample(frac=1, random_state=42).reset_index(drop=True)
df['career_aspiration'].value_counts()

career_aspiration
11    315
2     315
4     315
7     315
13    315
8     315
15    315
14    315
3     315
5     315
9     315
10    315
16    315
0     315
12    315
1     315
6     315
Name: count, dtype: int64

In [18]:
classes=df['career_aspiration'].unique()
df_list=[df[df['career_aspiration']==label]for label in classes]
df_list

[      gender  part_time_job  absence_days  extracurricular_activities  \
 0          0              0      0.507682                           0   
 12         1              0     -0.633604                           0   
 34         1              0     -1.014033                           0   
 52         1              1     -0.253175                           0   
 54         0              1      0.127253                           1   
 ...      ...            ...           ...                         ...   
 5270       0              0     -1.394461                           0   
 5272       1              0     -1.014033                           0   
 5281       1              0      0.127253                           0   
 5286       1              0     -1.014033                           0   
 5332       0              0     -0.633604                           1   
 
       weekly_self_study_hours  career_aspiration  math_score  history_score  \
 0                    0.844798

Train Test Split

In [19]:
X=df.drop('career_aspiration',axis=1)
y=df['career_aspiration']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
print("Train shape:",X_train.shape)
print("Test shape:",X_test.shape)

Train shape: (4284, 13)
Test shape: (1071, 13)


Training ,Testing Multiple Classifiers

In [20]:
# Define models
models = {
    "Logistic Regression": LogisticRegression(),
    "Support Vector Classifier": SVC(),
    "Random Forest Classifier": RandomForestClassifier(),
    "K Nearest Neighbors": KNeighborsClassifier(),
    "Decision Tree Classifier": DecisionTreeClassifier(),
    "Gaussian Naive Bayes": GaussianNB(),
    "AdaBoost Classifier": AdaBoostClassifier(),
    "Gradient Boosting Classifier": GradientBoostingClassifier(),
}

# Train and evaluate each model
for name, model in models.items():
    print("="*50)
    print("Model:", name)
    # Train the model
    model.fit(X_train, y_train)
    
    # Predict on test set
    y_pred = model.predict(X_test)
    
    # Calculate metrics
    accuracy = accuracy_score(y_test, y_pred)
    classification_rep = classification_report(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    
    # Print metrics
    print("Accuracy:", accuracy)
    print("Classification Report:\n", classification_rep)
    print("Confusion Matrix:\n", conf_matrix)
    


Model: Logistic Regression


c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy: 0.4024276377217554
Classification Report:
               precision    recall  f1-score   support

           0       0.39      0.41      0.40        74
           1       0.45      0.48      0.47        71
           2       0.38      0.27      0.32        67
           3       0.41      0.47      0.44        68
           4       0.23      0.09      0.13        75
           5       0.18      0.23      0.20        48
           6       0.48      0.77      0.59        57
           7       0.58      0.82      0.68        51
           8       0.27      0.13      0.18        60
           9       0.42      0.46      0.44        61
          10       0.31      0.25      0.28        64
          11       0.38      0.16      0.22        57
          12       0.41      0.48      0.44        62
          13       0.57      0.82      0.67        68
          14       0.15      0.07      0.10        70
          15       0.36      0.42      0.39        62
          16       0.39     

c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(ave

Accuracy: 0.13445378151260504
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        74
           1       0.30      0.76      0.43        71
           2       0.00      0.00      0.00        67
           3       0.00      0.00      0.00        68
           4       0.00      0.00      0.00        75
           5       0.05      0.46      0.09        48
           6       0.12      0.16      0.14        57
           7       0.22      0.65      0.33        51
           8       0.00      0.00      0.00        60
           9       0.11      0.18      0.14        61
          10       0.00      0.00      0.00        64
          11       0.00      0.00      0.00        57
          12       0.00      0.00      0.00        62
          13       0.00      0.00      0.00        68
          14       0.00      0.00      0.00        70
          15       0.12      0.24      0.16        62
          16       0.00    

c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(ave

Accuracy: 0.21942110177404295
Classification Report:
               precision    recall  f1-score   support

           0       0.17      0.05      0.08        74
           1       1.00      0.48      0.65        71
           2       0.26      0.55      0.35        67
           3       0.00      0.00      0.00        68
           4       0.17      0.11      0.13        75
           5       0.12      0.77      0.21        48
           6       0.00      0.00      0.00        57
           7       0.19      1.00      0.32        51
           8       0.00      0.00      0.00        60
           9       0.17      0.25      0.20        61
          10       0.00      0.00      0.00        64
          11       0.00      0.00      0.00        57
          12       0.00      0.00      0.00        62
          13       0.00      0.00      0.00        68
          14       0.00      0.00      0.00        70
          15       0.28      0.13      0.18        62
          16       0.37    

Selecting Best Model

In [21]:
model_rfc = RandomForestClassifier()

model_rfc.fit(X_train,y_train)

y_pred = model_rfc.predict(X_test)



print("confusion matrix \n: ", confusion_matrix(y_test,y_pred))
print("classification report \n: ", classification_report(y_test, y_pred))

confusion matrix 
:  [[72  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  1]
 [ 1 65  0  0  0  1  0  0  1  0  0  0  2  0  0  1  0]
 [ 0  0 66  0  0  0  0  0  0  0  1  0  0  0  0  0  0]
 [ 0  0  0 68  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  2 56  6  1  2  1  0  1  0  2  0  0  0  2]
 [ 2  1  0  0  3 37  0  0  2  0  0  1  2  0  0  0  0]
 [ 0  0  0  0  0  0 57  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  2  0  0  0 48  0  0  0  0  0  1  0  0  0]
 [ 6  0  0  0  1  1  6  0 43  0  0  0  1  0  0  1  1]
 [ 0  0  0  0  0  2  0  0  0 59  0  0  0  0  0  0  0]
 [ 0  0  1  5  0  0  0  2  0  0 56  0  0  0  0  0  0]
 [ 0  0  0  0  2  0  0  0  0  0  0 55  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 62  0  0  0  0]
 [ 0  0  0  3  0  0  0  0  0  0  0  0  0 65  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  2  0  0 68  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  0  0 61  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 56]]
classification report 
:                precision    recall 

In [22]:
import os
os.path.exists(r"C:\Users\Admin\Desktop\career aspiration")

False

In [23]:
os.path.exists(r"C:\Users\Admin\OneDrive\Desktop\career aspiration")

True

Saving Model, Encoder, Scaler for production

In [24]:

import pickle

with open("scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)

with open("encoder.pkl", "wb") as f:
    pickle.dump(encoder, f)

with open("model_rfc.pkl", "wb") as f:
    pickle.dump(model_rfc, f)


Prediction on new data

In [25]:
import pickle

encoder = pickle.load(open("encoder.pkl", "rb"))
scaler = pickle.load(open("scaler.pkl", "rb"))
model_rfc = pickle.load(open("model_rfc.pkl", "rb"))

In [26]:
import joblib
joblib.dump(model_rfc, "model_rfc.pkl", compress=3)

['model_rfc.pkl']

In [27]:



career_aspiration_map = {
    0: 'Software Engineer',
    1: 'Business Owner',
    2: 'Unknown',
    3: 'Banker',
    4: 'Lawyer',
    5: 'Accountant',
    6: 'Doctor',
    7: 'Real Estate Developer',
    8: 'Stock Investor',
    9: 'Construction Engineer',
    10: 'Artist',
    11: 'Game Developer',
    12: 'Government Officer',
    13: 'Teacher',
    14: 'Designer',
    15: 'Scientist',
    16: 'Writer'
}


def predict_career(gender, part_time_job, absence_days, extracurricular_activities, weekly_self_study_hours,
                   math_score, history_score, physics_score, chemistry_score, biology_score, english_score,
                   geography_score, total_score):
    """
    This function will use the trained model to predict career aspiration
    based on the input data provided.
    """
    # Create a DataFrame with the input values
    input_data = pd.DataFrame([[gender, part_time_job, absence_days, extracurricular_activities,
                                weekly_self_study_hours, math_score, history_score, physics_score,
                                chemistry_score, biology_score, english_score, geography_score,
                                total_score]],
                              columns=['gender', 'part_time_job', 'absence_days', 'extracurricular_activities',
                                       'weekly_self_study_hours', 'math_score', 'history_score', 'physics_score',
                                       'chemistry_score', 'biology_score', 'english_score', 'geography_score',
                                       'total_score'])

    # Encode categorical features using the loaded encoder
    input_data['gender'] = encoder.transform(input_data['gender'])
    input_data['part_time_job'] = encoder.transform(input_data['part_time_job'])
    input_data['extracurricular_activities'] = encoder.transform(input_data['extracurricular_activities'])

    # Scale numerical features using the loaded scaler
    input_data[['absence_days', 'weekly_self_study_hours', 'math_score', 'history_score',
              'physics_score', 'chemistry_score', 'biology_score',
              'english_score', 'geography_score']] = scaler.transform(
        input_data[['absence_days', 'weekly_self_study_hours', 'math_score', 'history_score',
              'physics_score', 'chemistry_score', 'biology_score',
              'english_score', 'geography_score']])

    # Make prediction using the pre-trained model
    result = model_rfc.predict(input_data)
    career_aspiration = career_aspiration_map[result[0]]

    return career_aspiration

In [28]:
# Predefined values (you can modify these based on your needs)
gender = 'male'
part_time_job = 'True'
absence_days = 2
extracurricular_activities = 'False'
weekly_self_study_hours = 8
math_score = 87
history_score = 76
physics_score = 84
chemistry_score = 80
biology_score = 90
english_score = 85
geography_score = 78
total_score = 640  


# Predict career aspiration
predicted_career = predict_career(gender, part_time_job, absence_days, extracurricular_activities, 
                                  weekly_self_study_hours, math_score, history_score, physics_score,
                                  chemistry_score, biology_score, english_score, geography_score,
                                  total_score)

# Print the result
print(f"Predicted Career Aspiration: {predicted_career}")

Predicted Career Aspiration: Unknown
